# Generated by Django 3.2.4 on 2021-07-04 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('first_name', models.CharField(max_length=200, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Telefonnummer')),
                ('conto_number', models.CharField(default=0, max_length=200, verbose_name='IBAN Nummer')),
                ('address', models.CharField(default=0, max_length=200, verbose_name='Strasse')),
                ('address_Nr', models.IntegerField(default=0, verbose_name='Strassennummer')),
                ('city', models.CharField(default=0, max_length=200, verbose_name='Wohnort')),
                ('city_code', models.IntegerField(default=0, verbose_name='PLZ')),
                ('first_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Vorname')),
                ('last_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Nachname')),
                ('activ', models.BooleanField(default=False, verbose_name='aktiv')),
            ],
        ),
        migrations.CreateModel(
            name='Mietobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200, verbose_name='Objektname')),
                ('building', models.CharField(choices=[('H1', 'H1'), ('H3', 'H3'), ('H3A', 'H3A'), ('H5', 'H5'), ('H5A', 'H5A')], default=0, max_length=10)),
                ('description', models.TextField(max_length=2048, verbose_name='Beschreibung')),
                ('photo', models.ImageField(default=0, upload_to='', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='Nebenkosten_Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200)),
                ('a_conto', models.CharField(choices=[('a', 'à conto'), ('p', 'pauschal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=2010)),
            ],
        ),
        migrations.CreateModel(
            name='Unterhalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('betrag', models.IntegerField(default=0)),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Nebenkosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aktiv', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.datetime(2021, 7, 4, 17, 13, 59, 303830))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 7, 4, 17, 13, 59, 303830))),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten_typ')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzinseingaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime(2021, 7, 4, 17, 13, 59, 309827))),
                ('month', models.CharField(choices=[('JA', 'Januar'), ('FE', 'Februar'), ('MA', 'März'), ('AP', 'April'), ('MA', 'Mai'), ('JN', 'Juni'), ('JU', 'Juli'), ('AU', 'August'), ('SE', 'September'), ('OK', 'Oktober'), ('NO', 'November'), ('DE', 'Dezember')], max_length=10)),
                ('betrag', models.IntegerField(default=0)),
                ('year', models.DateField(default=datetime.datetime(2021, 7, 4, 15, 13, 59, 310809, tzinfo=utc))),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Miete')),
                ('aktiv', models.BooleanField(default=False)),
                ('mietobject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
            ],
        ),
        migrations.AddField(
            model_name='mieter',
            name='mietzins',
            field=models.ManyToManyField(to='polls.Mietzins'),
        ),
        migrations.AddField(
            model_name='mieter',
            name='nebenkosten',
            field=models.ManyToManyField(to='polls.Nebenkosten'),
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('nebenkosten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten')),
            ],
        ),
        migrations.CreateModel(
            name='MietobjektSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.mietobjekt',),
        ),
        migrations.CreateModel(
            name='MietzinseingaengeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Mieteinnahmen',
                'verbose_name_plural': 'Mieteingänge',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.mietzinseingaenge',),
        ),
    ]
