# Generated by Django 3.2.4 on 2021-06-28 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('first_name', models.CharField(max_length=200, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nachname')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Telefonnummer')),
                ('conto_number', models.CharField(default=0, max_length=200, verbose_name='IBAN Nummer')),
                ('address', models.CharField(default=0, max_length=200, verbose_name='Strasse')),
                ('address_Nr', models.CharField(default=0, max_length=200, verbose_name='Strassennummer')),
                ('city', models.CharField(default=0, max_length=200, verbose_name='Wohnort')),
                ('city_code', models.IntegerField(default=0, verbose_name='PLZ')),
                ('first_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Vorname')),
                ('last_name_2nd', models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Nachname')),
                ('activ', models.BooleanField(default=False, verbose_name='aktiv')),
            ],
        ),
        migrations.CreateModel(
            name='Mietobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200, verbose_name='Objektname')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.IntegerField(default=0)),
                ('a_conto', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZahlungsTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nebenkosten_Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200)),
                ('a_conto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zahlungstyp')),
            ],
        ),
        migrations.CreateModel(
            name='Nebenkosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aktiv', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.datetime(2021, 6, 28, 19, 15, 33, 746363))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 6, 28, 19, 15, 33, 746363))),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten_typ')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzinseingaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.datetime(2021, 6, 28, 19, 15, 33, 747362))),
                ('month', models.CharField(choices=[('JA', 'Januar'), ('FE', 'Februar'), ('MA', 'März'), ('AP', 'April'), ('MA', 'Mai'), ('JN', 'Juni'), ('JU', 'Juli'), ('AU', 'August'), ('SE', 'September'), ('OK', 'Oktober'), ('NO', 'November'), ('DE', 'Dezember')], max_length=10)),
                ('betrag', models.IntegerField(default=0)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('nebenkosten', models.ManyToManyField(to='polls.Nebenkosten')),
            ],
        ),
        migrations.CreateModel(
            name='Mietzins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.IntegerField(default=0)),
                ('mietobject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('nebenkosten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten')),
            ],
        ),
    ]
