# Generated by Django 3.2.4 on 2021-06-28 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_kosten_mieter_mietobjekt_mietzins_mietzinseingaenge_nebenkosten_nebenkosten_typ_zahlungstyp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mietzinseingaenge',
            name='nebenkosten',
        ),
        migrations.RemoveField(
            model_name='nebenkosten',
            name='mieter',
        ),
        migrations.AddField(
            model_name='mieter',
            name='mietzins',
            field=models.ManyToManyField(to='polls.Mietzins'),
        ),
        migrations.AddField(
            model_name='mieter',
            name='nebenkosten',
            field=models.ManyToManyField(to='polls.Nebenkosten'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 22, 23, 410542)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 22, 23, 404545)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 22, 23, 404545)),
        ),
        migrations.AlterField(
            model_name='nebenkosten_typ',
            name='a_conto',
            field=models.CharField(choices=[('a', 'à conto'), ('p', 'pauschal')], max_length=10),
        ),
    ]
