# Generated by Django 3.2.4 on 2021-06-28 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210628_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=2010)),
            ],
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 35, 37, 779396)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 35, 37, 772400)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 19, 35, 37, 772400)),
        ),
        migrations.AddField(
            model_name='mietzinseingaenge',
            name='year',
            field=models.ForeignKey(default=2010, on_delete=django.db.models.deletion.CASCADE, to='polls.year'),
        ),
    ]
