# Generated by Django 3.2.4 on 2021-06-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_mietobjekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nebenkosten_Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200)),
                ('a_conto', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='a_conto',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Nebenkosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.IntegerField(default=0)),
                ('aktiv', models.IntegerField(default=0)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten_typ')),
            ],
        ),
    ]
