# Generated by Django 3.2.4 on 2021-06-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210623_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mietzinseingaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.IntegerField(default=0)),
                ('datum', models.DateTimeField()),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('nebenkosten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nebenkosten')),
            ],
        ),
    ]
