# Generated by Django 3.2.4 on 2021-07-04 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210704_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 16, 35, 441650)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='year',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 16, 35, 441650)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 16, 35, 435654)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 16, 35, 435654)),
        ),
    ]
