# Generated by Django 3.2.4 on 2021-07-06 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210706_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzins',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 2, 4, 298154)),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 2, 4, 298154)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 2, 4, 305150)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 2, 4, 299154)),
        ),
        migrations.AlterField(
            model_name='mietzinsprofil',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 20, 2, 4, 299154)),
        ),
        migrations.AlterField(
            model_name='unterhalt',
            name='project',
            field=models.CharField(default=0, max_length=200, verbose_name='Projekt'),
        ),
    ]
