# Generated by Django 3.2.4 on 2021-06-29 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210628_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZahlungsTyp',
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 18, 39, 52, 672212)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 18, 39, 52, 665235)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 18, 39, 52, 665235)),
        ),
    ]
