# Generated by Django 3.2.4 on 2021-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_kosten_mietzinseingaenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='0000', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2010', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='betrag',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nebenkosten_typ',
            name='a_conto',
            field=models.BooleanField(default=False),
        ),
    ]
