# Generated by Django 3.2.4 on 2021-06-29 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210629_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mietobjekt',
            name='a_conto',
        ),
        migrations.AlterField(
            model_name='mieter',
            name='address_Nr',
            field=models.IntegerField(default=0, verbose_name='Strassennummer'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 10, 4, 60481)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 10, 4, 54484)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 10, 4, 54484)),
        ),
    ]
