# Generated by Django 3.2.4 on 2021-06-29 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210629_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mietobjekt',
            name='rent',
        ),
        migrations.AlterField(
            model_name='mietobjekt',
            name='description',
            field=models.TextField(max_length=2048, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 28, 32, 50904)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 28, 32, 44907)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 28, 32, 44907)),
        ),
    ]
