# Generated by Django 3.2.4 on 2021-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210625_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Mietzinseingaenge',
        ),
    ]
