# Generated by Django 3.2.4 on 2021-06-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210625_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mietzinseingaenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('betrag', models.IntegerField(default=0)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mieter')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.year')),
            ],
        ),
    ]
