# Generated by Django 3.2.4 on 2021-07-04 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210704_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietobjekt',
            name='photo',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 24, 19, 42751)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='year',
            field=models.DateField(default=2021),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 24, 19, 36754)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 17, 24, 19, 36754)),
        ),
    ]
