# Generated by Django 3.2.4 on 2021-06-29 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210629_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='mietobjekt',
            name='photo',
            field=models.ImageField(default=0, upload_to='', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='mietzins',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mietzins',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Miete'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 35, 47, 609212)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 35, 47, 601235)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 19, 35, 47, 601235)),
        ),
    ]
