# Generated by Django 3.2.4 on 2021-06-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210629_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='MietzinseingaengeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Mieteinnahmen',
                'verbose_name_plural': 'Mieteingänge',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.mietzinseingaenge',),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 18, 56, 15, 594106)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 18, 56, 15, 587111)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 18, 56, 15, 587111)),
        ),
    ]
