# Generated by Django 3.2.4 on 2021-06-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_mietzinseingaenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieter',
            name='address',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='mieter',
            name='address_Nr',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='mieter',
            name='city',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='mieter',
            name='city_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 11, 33, 262111)),
        ),
        migrations.AddField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 11, 33, 262111)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 11, 33, 262111)),
        ),
    ]
