# Generated by Django 3.2.4 on 2021-07-05 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210704_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 23, 23, 296255)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='year',
            field=models.ForeignKey(default=2010, on_delete=django.db.models.deletion.CASCADE, to='polls.year'),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 23, 23, 290258)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 23, 23, 290258)),
        ),
    ]
