# Generated by Django 3.2.4 on 2021-07-05 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210705_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 25, 56, 524558)),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='year',
            field=models.DateField(blank=True, default=2021),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 25, 56, 518580)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 16, 25, 56, 518580)),
        ),
    ]
