# Generated by Django 3.2.4 on 2021-07-02 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210630_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 54, 54, 320540)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 54, 54, 314543)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 13, 54, 54, 314543)),
        ),
        migrations.CreateModel(
            name='Unterhalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('betrag', models.IntegerField(default=0)),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mietobjekt')),
            ],
        ),
    ]
