# Generated by Django 3.2.4 on 2021-07-02 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210702_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='MietobjektSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.mietobjekt',),
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='building',
            field=models.CharField(choices=[('H1', 'H1'), ('H3', 'H3'), ('H3A', 'H3A'), ('H5', 'H5'), ('H5A', 'H5A')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 15, 0, 42, 790592)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 15, 0, 42, 784596)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 15, 0, 42, 784596)),
        ),
    ]
