# Generated by Django 3.2.4 on 2021-06-26 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210626_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 22, 50, 839333)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 22, 50, 839333)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 22, 50, 839333)),
        ),
        migrations.AlterField(
            model_name='zahlungstyp',
            name='typ',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
