# Generated by Django 3.2.4 on 2021-06-26 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20210626_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 28, 57, 274722)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 28, 57, 274722)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 28, 57, 274722)),
        ),
        migrations.AlterField(
            model_name='nebenkosten_typ',
            name='a_conto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zahlungstyp'),
        ),
    ]
