# Generated by Django 3.2.4 on 2021-06-26 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210626_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieter',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Vorname: '),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Nachname: '),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 10, 37, 50, 393417)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 10, 37, 50, 393417)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 10, 37, 50, 393417)),
        ),
    ]
