# Generated by Django 3.2.4 on 2021-06-26 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210626_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieter',
            name='compagny',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='address',
            field=models.CharField(default=0, max_length=200, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='address_Nr',
            field=models.CharField(default=0, max_length=200, verbose_name='Strassennummer'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='city',
            field=models.CharField(default=0, max_length=200, verbose_name='Wohnort'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='city_code',
            field=models.IntegerField(default=0, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='first_name_2nd',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Vorname'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='last_name_2nd',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zweitmieter Nachname'),
        ),
        migrations.AlterField(
            model_name='mieter',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 15, 52, 144369)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 15, 52, 144369)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 15, 52, 144369)),
        ),
    ]
