# Generated by Django 3.2.4 on 2021-06-26 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20210626_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieter',
            name='activ',
            field=models.BooleanField(default=False, verbose_name='aktiv'),
        ),
        migrations.AddField(
            model_name='mieter',
            name='conto_number',
            field=models.CharField(default=0, max_length=200, verbose_name='IBAN Nummer'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 22, 54, 704870)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 22, 54, 704870)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 22, 54, 704870)),
        ),
    ]
