# Generated by Django 3.2.4 on 2021-06-26 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210626_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mietzinse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('rent', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='mieter',
            old_name='compagny',
            new_name='company',
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Objektname'),
        ),
        migrations.AlterField(
            model_name='mietobjekt',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 37, 9, 701254)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 37, 9, 701254)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 37, 9, 701254)),
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='mietzins',
            field=models.ManyToManyField(to='polls.Mietzinse'),
        ),
    ]
