# Generated by Django 3.2.4 on 2021-06-26 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20210626_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mietobjekt',
            name='mietzins',
        ),
        migrations.AddField(
            model_name='mietobjekt',
            name='mietzins',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.mietzinse'),
        ),
        migrations.AlterField(
            model_name='mietzinseingaenge',
            name='datum',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 49, 29, 516320)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 49, 29, 516320)),
        ),
        migrations.AlterField(
            model_name='nebenkosten',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 16, 49, 29, 516320)),
        ),
    ]
